// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;
//將資料驗證轉換過來
[ModelMetadataType(typeof(OrderDMT))]
public partial class OrderD
{

}
public partial class OrderDMT
{
    public string Id { get; set; }

    public int ItemNo { get; set; }

    public int? ProductId { get; set; }

    public int? Price { get; set; }

    public int? QTY { get; set; }

    public int? Total { get; set; }
}