// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TEST_MVC.Models;
//將資料驗證轉換過來
[ModelMetadataType(typeof(OrderMMT))]
public partial class OrderM
{
}
public partial class OrderMMT
{
    [DisplayName("訂單編號")]
    public string Id { get; set; }
    [DisplayName("客戶編號")]
    [Required(ErrorMessage = "必填")]
    public int? CustomerId { get; set; }
    [DisplayName("訂單總價")]
    [Required(ErrorMessage = "必填")]
    public int? TotalPrice { get; set; }
    [DisplayName("建檔日期")]
    public DateTime? CreactDate { get; set; }
    [DisplayName("建檔人員")]
    public string CreactUser { get; set; }
    [DisplayName("修改日期")]
    public DateTime? EditDate { get; set; }
    [DisplayName("修改人員")]
    public string EditUser { get; set; }
}