// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated> #nullable disable 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;

namespace TEST_MVC.Models;

//將資料驗證轉換過來
[ModelMetadataType(typeof(ProductMT))]
public partial class Product
{
}
public partial class ProductMT
{
    public int Id { get; set; }
    [DisplayName("商品名稱")]
    [Required(ErrorMessage = "必填")]
    public string Name { get; set; }
    [DisplayName("價格")]
    [Required(ErrorMessage = "必填")]
    [Range(1, 100000, ErrorMessage = "超出範圍")]
    public int? Price { get; set; }
    [DisplayName("庫存")]
    [Required(ErrorMessage = "必填")]
    public int? Stock { get; set; }
    [DisplayName("圖片")]
    public string ImageUrl { get; set; }
    [DisplayName("商品類別")]
    [Required(ErrorMessage = "必填")]
    public int ProductTypeId { get; set; }
    [DisplayName("建檔日期")]
    public DateTime CreatDate { get; set; }
    [DisplayName("建檔人員")]
    public string CreatUser { get; set; }
    [DisplayName("修改日期")]
    public DateTime? EditDate { get; set; }
    [DisplayName("修改人員")]
    public string EditUser { get; set; }
}