// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;
//將資料驗證轉換過來
[ModelMetadataType(typeof(ProductTypeMT))]
public partial class ProductType
{

}
public partial class ProductTypeMT
{
    public int Id { get; set; }

    public string name { get; set; }

    public DateTime CreatDate { get; set; }

    public DateTime? EditDate { get; set; }
}