// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TEST_MVC.Models;
//將資料驗證轉換過來
[ModelMetadataType(typeof(UserMT))]
public partial class User
{
}
public partial class UserMT
{
    public int Id { get; set; }
    [Required(ErrorMessage = "必填")]
    public string Name { get; set; }
    [Required(ErrorMessage = "必填")]
    public string PassWord { get; set; }
}