// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Tel { get; set; }

    public string Addr { get; set; }

    public DateTime? CreactDate { get; set; }

    public string CreactUser { get; set; }

    public DateTime? EditDate { get; set; }

    public string EditUser { get; set; }
}