// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;

public partial class OrderM
{
    public string Id { get; set; }

    public int? CustomerId { get; set; }

    public int? TotalPrice { get; set; }

    public DateTime? CreactDate { get; set; }

    public string CreactUser { get; set; }

    public DateTime? EditDate { get; set; }

    public string EditUser { get; set; }

}