// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;

public partial class OrderD
{
    public string Id { get; set; }

    public int ItemNo { get; set; }

    public int? ProductId { get; set; }

    public int? Price { get; set; }

    public int? QTY { get; set; }

    public int? Total { get; set; }
}