// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;

public partial class ProductType
{
    public int Id { get; set; }

    public string name { get; set; }

    public DateTime CreatDate { get; set; }

    public string CreatUser { get; set; }

    public DateTime? EditDate { get; set; }

    public string EditUser { get; set; }
}