// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEST_MVC.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Price { get; set; }

    public int? Stock { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreatDate { get; set; }

    public DateTime? EditDate { get; set; }
}